Add support for C_DeriveKey PKCS#11 function
LudovicRousseau/PyKCS11 pull request #72
Opened 2020-06-21 17:10 UTC by balsingh1991

Add support for CK_KEY_DERIVATION_STRING_DATA struct for use as mechanism parameters
Add support for DUKPT key derivation
Add support for ECIES encrypt/decrypt operations
Note: For DUKPT and ECIES operations, underlying cryto implementation must support it otherwise CKR_MECHANISM_INVALID error is encountered.

2020-06-22 16:13 UTC, LudovicRousseau commented
It looks nice.

Can yo provide a Unitary Test as the ones in the `test/` directory?
The idea is to:
- test the wrapper is working as expected
- check for regression in case of future code change
- "document" how to use the function

2020-06-22 23:27 UTC, balsingh1991 commented
I had created few unit tests. Unfortunately, for my use case mechanisms involved are not standard, thus, softhsm will not support it.
Trying to include derive test for CKM_ECDH1_DERIVE, but getting CKR_MECHANISM_PARAM_INVALID from softhsm. I'll add another commit when I resolve it.
Thanks!

2021-02-18 08:06 UTC, LudovicRousseau commented
Allo @balsingh1991, any progress on the use of SoftHSM with your patches?

2021-02-20 08:04 UTC, balsingh1991 commented
Hi,

My apologies for leaving this stray for long. I will check and report
sometime next week.

Thank you for bringing this to my attention!


- Baljinder Singh

On Thu., Feb. 18, 2021, 1:36 p.m. Ludovic Rousseau, <
notifications@github.com> wrote:

> Allo @balsingh1991 <https://github.com/balsingh1991>, any progress on the
> use of SoftHSM with your patches?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LudovicRousseau/PyKCS11/pull/72#issuecomment-781136920>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF2JAZ3YHOPF5UE6PHUPM73S7TC73ANCNFSM4OD6G2DA>
> .
>

2022-08-05 11:26 UTC, LudovicRousseau requested changes
It would be perfect if you could:
- rebase your patches above master
- split the patches with only one new feature per patch

2022-08-05 11:26 UTC, LudovicRousseau commented on src/pykcs11.i
> +#define CKM_DES2_DUKPT_MAC             (CKM_VENDOR_DEFINED + 0x612)
I can't include vendor specific mechanisms.

Are these mechanisms planned for a future version of PKCS#11 standard?

2022-08-06 18:00 UTC, closed without merging